"""
train_2.py
--------
Trains and compares three classifiers (Logistic Regression, Random Forest, XGBoost) 
to predict next-day AMZN price movement direction (Negative / Neutral / Positive) 
from financial features, indices, and volatility metrics.

Expected input: Daily labeled data CSV (e.g., data/processed/labeled_2_normalized.csv)
Usage:
    python src/train_2.py --data data/processed/labeled_2_normalized.csv --out models/model.pkl
"""

import argparse
import json 
from pathlib import Path
import pickle
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.utils.class_weight import compute_sample_weight
from xgboost import XGBClassifier

RANDOM_STATE = 42  # Seed for reproducibility
TEST_SIZE = 0.20     # 20% of dataset held out for chronological testing
TARGET_COL = "label" # Target column to predict

# Columns to explicitly exclude from model inputs (dates, targets, raw price levels, or leaks)
NON_FEATURE_COLS = {
    "date",
    TARGET_COL,
    "score_range",
    "amzn_next_return",
    "amzn_close",
    "amzn",
    "ixic",
    "spx",
    "sp500_25",
    "nasdaqndxt",
    "vixcls",
    "vxazn",
    # Exclude raw dollar-level SMAs (ratios like amzn_ratio_sma_20 will still be included)
   # "amzn_sma_5", "amzn_sma_10", "amzn_sma_20",
   # "ixic_sma_5", "ixic_sma_10", "ixic_sma_20",
   # "spx_sma_5", "spx_sma_10", "spx_sma_20",
}


def load_data(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=["date"])
    df = df.sort_values("date").reset_index(drop=True)
    return df


def get_feature_columns(df: pd.DataFrame) -> list:
    """Selects all numeric columns except those specified in NON_FEATURE_COLS."""
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    return [c for c in numeric_cols if c not in NON_FEATURE_COLS]


def to_jsonable(obj): 
    """Recursively converts numpy types to plain Python types for json export."""
    if isinstance(obj, dict):
        return {k: to_jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_jsonable(v) for v in obj]
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    return obj


def evaluate(model, X_test, y_test, class_order, model_name: str, label_encoder: LabelEncoder = None) -> dict:
    y_pred = model.predict(X_test) 

    # Decode numeric predictions back to string labels if generated by XGBoost
    if label_encoder is not None and len(y_pred) > 0 and isinstance(y_pred[0], (int, np.integer)):
        y_pred = label_encoder.inverse_transform(y_pred)

    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred, labels=class_order)
    cm_df = pd.DataFrame(
        cm,
        index=[f"actual_{c}" for c in class_order],
        columns=[f"pred_{c}" for c in class_order],
    )

    report = classification_report(
        y_test, y_pred, labels=class_order, output_dict=True, zero_division=0
    )

    macro_f1 = f1_score(y_test, y_pred, labels=class_order, average="macro", zero_division=0)

    print(f"\n{'=' * 60}")
    print(model_name)
    print("=" * 60)
    print(f"Accuracy : {acc:.4f}")
    print(f"Macro F1 : {macro_f1:.4f}")
    print("\nConfusion matrix:")
    print(cm_df.to_string())
    print("\nPer-class F1 / precision / recall:")
    for cls in class_order:
        r = report[cls]
        print(
            f"  {cls:10s} f1={r['f1-score']:.4f}  "
            f"precision={r['precision']:.4f}  recall={r['recall']:.4f}  support={int(r['support'])}"
        )

    return {
        "model_name": model_name,
        "accuracy": acc,
        "macro_f1": macro_f1,
        "confusion_matrix": cm.tolist(),
        "confusion_matrix_labels": class_order,
        "per_class_f1": {cls: report[cls]["f1-score"] for cls in class_order},
        "classification_report": report,
    }


def main(data_path: Path, out_path: Path):
    df = load_data(data_path)
    feature_cols = get_feature_columns(df)

    before = len(df)
    df = df.dropna(subset=feature_cols + [TARGET_COL]).reset_index(drop=True)
    dropped = before - len(df)
    if dropped:
        print(f"Dropped {dropped} row(s) with missing values in features/target.")

    print(f"Dataset shape: {df.shape}")
    print(f"Feature columns ({len(feature_cols)}): {feature_cols}")
    print("\nClass distribution:")
    print(df[TARGET_COL].value_counts())

    expected = ["Negative", "Neutral", "Positive"]
    class_order = expected if set(df[TARGET_COL].unique()) == set(expected) else sorted(
        df[TARGET_COL].unique()
    )

    X = df[feature_cols].to_numpy()
    y = df[TARGET_COL].to_numpy()

    # --- CHRONOLOGICAL TIME-SERIES SPLIT ---
    split_idx = int(len(df) * (1 - TEST_SIZE))
    
    X_train, X_test = X[:split_idx], X[split_idx:]
    y_train, y_test = y[:split_idx], y[split_idx:]
    
    print(f"\nTime-Series Split Successful:")
    print(f"  Training samples (Historical): {len(X_train)} rows")
    print(f"  Testing samples (Future):     {len(X_test)} rows")
    # ----------------------------------------

    # Standardize Features
    scaler = StandardScaler() 
    X_train_scaled = scaler.fit_transform(X_train) 
    X_test_scaled = scaler.transform(X_test) 

    # Prepare integer encoding & sample weights for XGBoost
    label_encoder = LabelEncoder()
    y_train_encoded = label_encoder.fit_transform(y_train)
    sample_weights_train = compute_sample_weight("balanced", y_train)

    # 1. Logistic Regression
    logreg = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=RANDOM_STATE) 
    logreg.fit(X_train_scaled, y_train)

    # 2. Random Forest
    rf = RandomForestClassifier(n_estimators=300, class_weight="balanced", random_state=RANDOM_STATE) 
    rf.fit(X_train_scaled, y_train) 

    # 3. XGBoost
    xgb = XGBClassifier(
        n_estimators=500,       # Increase trees from 200 to 500
        learning_rate=0.015,    # Lower learning rate for finer optimization steps
        max_depth=3,            # Keep shallow trees (depth 3) to prevent memorizing noise
        subsample=0.7,          # Randomly sample 70% of rows per tree
        colsample_bytree=0.7,   # Randomly sample 70% of features per tree
        reg_alpha=0.1,          # L1 regularization to prune unhelpful features
        reg_lambda=1.0,         # L2 regularization to stabilize weights
        random_state=RANDOM_STATE,
        eval_metric="mlogloss"
    )
    xgb.fit(X_train_scaled, y_train_encoded, sample_weight=sample_weights_train)

    # Evaluate Models
    results = {
        "LogisticRegression": evaluate(logreg, X_test_scaled, y_test, class_order, "Logistic Regression"),
        "RandomForest": evaluate(rf, X_test_scaled, y_test, class_order, "Random Forest"),
        "XGBoost": evaluate(xgb, X_test_scaled, y_test, class_order, "XGBoost", label_encoder=label_encoder),
    }

    models_dict = {
        "LogisticRegression": logreg,
        "RandomForest": rf,
        "XGBoost": xgb,
    }

    # Select best model based on Macro F1 score
    best_name = max(results, key=lambda k: results[k]["macro_f1"])
    best_model = models_dict[best_name]
    print(f"\nBest model: {best_name}  (macro F1 = {results[best_name]['macro_f1']:.4f})") 

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "wb") as f:
        pickle.dump(
            {
                "model": best_model,
                "model_name": best_name,
                "scaler": scaler,
                "feature_columns": feature_cols,
                "classes": class_order,
                "label_encoder": label_encoder if best_name == "XGBoost" else None,
            },
            f,
        )
    print(f"Saved best model + scaler -> {out_path}")

    # Save metrics JSON alongside the model pickle
    metrics_path = out_path.parent / "metrics.json"
    with open(metrics_path, "w") as f:
        json.dump(to_jsonable(results), f, indent=2)
    print(f"Saved full metrics -> {metrics_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=Path("data/processed/labeled_2_normalized.csv"))
    parser.add_argument("--out", type=Path, default=Path("models/model_2.pkl"))
    args = parser.parse_args()
    main(args.data, args.out)
